import express from 'express';
import { registerUser,loginUser ,getProfile,updateProfile,bookAppointment,listAppointments} from '../controllers/userController.js';
import authUser from '../middleware/authUser.js';
import upload from "../middleware/multer.js";
const userRouter = express.Router();
userRouter.post('/register', registerUser);
userRouter.post('/login', loginUser);
userRouter.post('/profile',authUser, getProfile);
userRouter.put('/profile',authUser,upload.single('image'), updateProfile);
userRouter.post('/book-appointment',authUser, bookAppointment);
userRouter.get('/my-appointments',authUser, listAppointments);
export default userRouter;
